# Auto-generated by /Users/lekangzoukang/git/nipype2pydra/nipype2pydra/package.py, do not edit as it will be overwritten

src_pkg_version = "1.10.1"
nipype2pydra_version = "0.3.6"
post_release = "1101036"
        